export const statColumns = [
  { abbrev: 'Min',   field: 'minutes',        label: 'Minutos jugados' },
  { abbrev: 'G',     field: 'goals',          label: 'Goles' },
  { abbrev: 'A',     field: 'assists',        label: 'Asistencias' },
  { abbrev: 'TaP',   field: 'shots_on_target',  label: 'Tiros a portería' },
  { abbrev: 'TfP',   field: 'shots_off_target', label: 'Tiros fuera' },
  { abbrev: 'Blq',   field: 'blocked_shots',  label: 'Tiros bloqueados' },
  { abbrev: 'Ent',   field: 'tackles',        label: 'Entradas' },
  { abbrev: 'Int',   field: 'interceptions',  label: 'Intercepciones' },
  { abbrev: 'Pas',   field: 'passes',         label: 'Pases (÷10)' },
  { abbrev: 'Cen',   field: 'crosses',        label: 'Centros' },
  { abbrev: 'FaF',   field: 'fouls_won',      label: 'Faltas a favor' },
  { abbrev: 'FaC',   field: 'fouls_conceded', label: 'Faltas cometidas' },
  { abbrev: 'FdJ',   field: 'offsides',       label: 'Fuera de juego' },
  { abbrev: 'PenG',  field: 'penalties_won',  label: 'Penaltis ganados' },
  { abbrev: 'Atj',   field: 'saves',          label: 'Atajadas' },
  { abbrev: 'PenAt', field: 'penalty_saves',  label: 'Penaltis atajados' },
  { abbrev: 'PenF',  field: 'penalty_misses', label: 'Penaltis fallados' },
  { abbrev: 'GenC',  field: 'goals_conceded', label: 'Goles en contra' },
  { abbrev: 'TA',    field: 'yellow_cards',   label: 'Tarjeta amarilla' },
  { abbrev: 'TR',    field: 'red_cards',      label: 'Tarjeta roja' },
  { abbrev: 'AaP',   field: 'own_goals',      label: 'Autogol' },
  { abbrev: 'Por',   field: 'clean_sheets',   label: 'Portería a cero' },
];
