-- Generated by sync-schedule.mjs --sql. Run in the Supabase SQL editor.
-- Sets matches.matchday_id + match_date from the WC 2026 schedule CSV.
BEGIN;

-- Group stage (72 matches) — joined by group + team pair
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-11T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'A' AND ((team_a = 'MEX' AND team_b = 'RSA') OR (team_a = 'RSA' AND team_b = 'MEX'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-11T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'A' AND ((team_a = 'KOR' AND team_b = 'CZE') OR (team_a = 'CZE' AND team_b = 'KOR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-12T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'B' AND ((team_a = 'CAN' AND team_b = 'BIH') OR (team_a = 'BIH' AND team_b = 'CAN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-12T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'D' AND ((team_a = 'USA' AND team_b = 'PAR') OR (team_a = 'PAR' AND team_b = 'USA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-13T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'B' AND ((team_a = 'QAT' AND team_b = 'SUI') OR (team_a = 'SUI' AND team_b = 'QAT'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-13T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'C' AND ((team_a = 'BRA' AND team_b = 'MAR') OR (team_a = 'MAR' AND team_b = 'BRA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-13T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'C' AND ((team_a = 'HAI' AND team_b = 'SCO') OR (team_a = 'SCO' AND team_b = 'HAI'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-14T00:00:00-04:00' WHERE stage = 'group' AND group_name = 'D' AND ((team_a = 'AUS' AND team_b = 'TUR') OR (team_a = 'TUR' AND team_b = 'AUS'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-14T13:00:00-04:00' WHERE stage = 'group' AND group_name = 'E' AND ((team_a = 'GER' AND team_b = 'CUW') OR (team_a = 'CUW' AND team_b = 'GER'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-14T16:00:00-04:00' WHERE stage = 'group' AND group_name = 'F' AND ((team_a = 'NED' AND team_b = 'JPN') OR (team_a = 'JPN' AND team_b = 'NED'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-14T19:00:00-04:00' WHERE stage = 'group' AND group_name = 'E' AND ((team_a = 'CIV' AND team_b = 'ECU') OR (team_a = 'ECU' AND team_b = 'CIV'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-14T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'F' AND ((team_a = 'SWE' AND team_b = 'TUN') OR (team_a = 'TUN' AND team_b = 'SWE'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-15T12:00:00-04:00' WHERE stage = 'group' AND group_name = 'H' AND ((team_a = 'ESP' AND team_b = 'CPV') OR (team_a = 'CPV' AND team_b = 'ESP'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-15T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'G' AND ((team_a = 'BEL' AND team_b = 'EGY') OR (team_a = 'EGY' AND team_b = 'BEL'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-15T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'H' AND ((team_a = 'KSA' AND team_b = 'URU') OR (team_a = 'URU' AND team_b = 'KSA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-15T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'G' AND ((team_a = 'IRN' AND team_b = 'NZL') OR (team_a = 'NZL' AND team_b = 'IRN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-16T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'I' AND ((team_a = 'FRA' AND team_b = 'SEN') OR (team_a = 'SEN' AND team_b = 'FRA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-16T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'I' AND ((team_a = 'IRQ' AND team_b = 'NOR') OR (team_a = 'NOR' AND team_b = 'IRQ'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-16T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'J' AND ((team_a = 'ARG' AND team_b = 'ALG') OR (team_a = 'ALG' AND team_b = 'ARG'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-17T00:00:00-04:00' WHERE stage = 'group' AND group_name = 'J' AND ((team_a = 'AUT' AND team_b = 'JOR') OR (team_a = 'JOR' AND team_b = 'AUT'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-17T13:00:00-04:00' WHERE stage = 'group' AND group_name = 'K' AND ((team_a = 'POR' AND team_b = 'COD') OR (team_a = 'COD' AND team_b = 'POR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-17T16:00:00-04:00' WHERE stage = 'group' AND group_name = 'L' AND ((team_a = 'ENG' AND team_b = 'CRO') OR (team_a = 'CRO' AND team_b = 'ENG'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-17T19:00:00-04:00' WHERE stage = 'group' AND group_name = 'L' AND ((team_a = 'GHA' AND team_b = 'PAN') OR (team_a = 'PAN' AND team_b = 'GHA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1'), match_date = '2026-06-17T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'K' AND ((team_a = 'UZB' AND team_b = 'COL') OR (team_a = 'COL' AND team_b = 'UZB'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-18T12:00:00-04:00' WHERE stage = 'group' AND group_name = 'A' AND ((team_a = 'CZE' AND team_b = 'RSA') OR (team_a = 'RSA' AND team_b = 'CZE'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-18T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'B' AND ((team_a = 'SUI' AND team_b = 'BIH') OR (team_a = 'BIH' AND team_b = 'SUI'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-18T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'B' AND ((team_a = 'CAN' AND team_b = 'QAT') OR (team_a = 'QAT' AND team_b = 'CAN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-18T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'A' AND ((team_a = 'MEX' AND team_b = 'KOR') OR (team_a = 'KOR' AND team_b = 'MEX'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-19T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'D' AND ((team_a = 'USA' AND team_b = 'AUS') OR (team_a = 'AUS' AND team_b = 'USA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-19T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'C' AND ((team_a = 'SCO' AND team_b = 'MAR') OR (team_a = 'MAR' AND team_b = 'SCO'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-19T20:30:00-04:00' WHERE stage = 'group' AND group_name = 'C' AND ((team_a = 'BRA' AND team_b = 'HAI') OR (team_a = 'HAI' AND team_b = 'BRA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-19T23:00:00-04:00' WHERE stage = 'group' AND group_name = 'D' AND ((team_a = 'TUR' AND team_b = 'PAR') OR (team_a = 'PAR' AND team_b = 'TUR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-20T13:00:00-04:00' WHERE stage = 'group' AND group_name = 'F' AND ((team_a = 'NED' AND team_b = 'SWE') OR (team_a = 'SWE' AND team_b = 'NED'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-20T16:00:00-04:00' WHERE stage = 'group' AND group_name = 'E' AND ((team_a = 'GER' AND team_b = 'CIV') OR (team_a = 'CIV' AND team_b = 'GER'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-20T20:00:00-04:00' WHERE stage = 'group' AND group_name = 'E' AND ((team_a = 'ECU' AND team_b = 'CUW') OR (team_a = 'CUW' AND team_b = 'ECU'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-21T00:00:00-04:00' WHERE stage = 'group' AND group_name = 'F' AND ((team_a = 'TUN' AND team_b = 'JPN') OR (team_a = 'JPN' AND team_b = 'TUN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-21T12:00:00-04:00' WHERE stage = 'group' AND group_name = 'H' AND ((team_a = 'ESP' AND team_b = 'KSA') OR (team_a = 'KSA' AND team_b = 'ESP'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-21T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'G' AND ((team_a = 'BEL' AND team_b = 'IRN') OR (team_a = 'IRN' AND team_b = 'BEL'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-21T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'H' AND ((team_a = 'URU' AND team_b = 'CPV') OR (team_a = 'CPV' AND team_b = 'URU'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-21T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'G' AND ((team_a = 'NZL' AND team_b = 'EGY') OR (team_a = 'EGY' AND team_b = 'NZL'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-22T13:00:00-04:00' WHERE stage = 'group' AND group_name = 'J' AND ((team_a = 'ARG' AND team_b = 'AUT') OR (team_a = 'AUT' AND team_b = 'ARG'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-22T17:00:00-04:00' WHERE stage = 'group' AND group_name = 'I' AND ((team_a = 'FRA' AND team_b = 'IRQ') OR (team_a = 'IRQ' AND team_b = 'FRA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-22T20:00:00-04:00' WHERE stage = 'group' AND group_name = 'I' AND ((team_a = 'NOR' AND team_b = 'SEN') OR (team_a = 'SEN' AND team_b = 'NOR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-22T23:00:00-04:00' WHERE stage = 'group' AND group_name = 'J' AND ((team_a = 'JOR' AND team_b = 'ALG') OR (team_a = 'ALG' AND team_b = 'JOR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-23T13:00:00-04:00' WHERE stage = 'group' AND group_name = 'K' AND ((team_a = 'POR' AND team_b = 'UZB') OR (team_a = 'UZB' AND team_b = 'POR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-23T16:00:00-04:00' WHERE stage = 'group' AND group_name = 'L' AND ((team_a = 'ENG' AND team_b = 'GHA') OR (team_a = 'GHA' AND team_b = 'ENG'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-23T19:00:00-04:00' WHERE stage = 'group' AND group_name = 'L' AND ((team_a = 'PAN' AND team_b = 'CRO') OR (team_a = 'CRO' AND team_b = 'PAN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2'), match_date = '2026-06-23T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'K' AND ((team_a = 'COL' AND team_b = 'COD') OR (team_a = 'COD' AND team_b = 'COL'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-24T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'B' AND ((team_a = 'SUI' AND team_b = 'CAN') OR (team_a = 'CAN' AND team_b = 'SUI'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-24T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'B' AND ((team_a = 'BIH' AND team_b = 'QAT') OR (team_a = 'QAT' AND team_b = 'BIH'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-24T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'C' AND ((team_a = 'SCO' AND team_b = 'BRA') OR (team_a = 'BRA' AND team_b = 'SCO'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-24T18:00:00-04:00' WHERE stage = 'group' AND group_name = 'C' AND ((team_a = 'MAR' AND team_b = 'HAI') OR (team_a = 'HAI' AND team_b = 'MAR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-24T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'A' AND ((team_a = 'CZE' AND team_b = 'MEX') OR (team_a = 'MEX' AND team_b = 'CZE'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-24T21:00:00-04:00' WHERE stage = 'group' AND group_name = 'A' AND ((team_a = 'RSA' AND team_b = 'KOR') OR (team_a = 'KOR' AND team_b = 'RSA'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-25T16:00:00-04:00' WHERE stage = 'group' AND group_name = 'E' AND ((team_a = 'CUW' AND team_b = 'CIV') OR (team_a = 'CIV' AND team_b = 'CUW'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-25T16:00:00-04:00' WHERE stage = 'group' AND group_name = 'E' AND ((team_a = 'ECU' AND team_b = 'GER') OR (team_a = 'GER' AND team_b = 'ECU'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-25T19:00:00-04:00' WHERE stage = 'group' AND group_name = 'F' AND ((team_a = 'JPN' AND team_b = 'SWE') OR (team_a = 'SWE' AND team_b = 'JPN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-25T19:00:00-04:00' WHERE stage = 'group' AND group_name = 'F' AND ((team_a = 'TUN' AND team_b = 'NED') OR (team_a = 'NED' AND team_b = 'TUN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-25T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'D' AND ((team_a = 'TUR' AND team_b = 'USA') OR (team_a = 'USA' AND team_b = 'TUR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-25T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'D' AND ((team_a = 'PAR' AND team_b = 'AUS') OR (team_a = 'AUS' AND team_b = 'PAR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-26T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'I' AND ((team_a = 'NOR' AND team_b = 'FRA') OR (team_a = 'FRA' AND team_b = 'NOR'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-26T15:00:00-04:00' WHERE stage = 'group' AND group_name = 'I' AND ((team_a = 'SEN' AND team_b = 'IRQ') OR (team_a = 'IRQ' AND team_b = 'SEN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-26T20:00:00-04:00' WHERE stage = 'group' AND group_name = 'H' AND ((team_a = 'CPV' AND team_b = 'KSA') OR (team_a = 'KSA' AND team_b = 'CPV'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-26T20:00:00-04:00' WHERE stage = 'group' AND group_name = 'H' AND ((team_a = 'URU' AND team_b = 'ESP') OR (team_a = 'ESP' AND team_b = 'URU'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-26T23:00:00-04:00' WHERE stage = 'group' AND group_name = 'G' AND ((team_a = 'EGY' AND team_b = 'IRN') OR (team_a = 'IRN' AND team_b = 'EGY'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-26T23:00:00-04:00' WHERE stage = 'group' AND group_name = 'G' AND ((team_a = 'NZL' AND team_b = 'BEL') OR (team_a = 'BEL' AND team_b = 'NZL'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-27T17:00:00-04:00' WHERE stage = 'group' AND group_name = 'L' AND ((team_a = 'PAN' AND team_b = 'ENG') OR (team_a = 'ENG' AND team_b = 'PAN'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-27T17:00:00-04:00' WHERE stage = 'group' AND group_name = 'L' AND ((team_a = 'CRO' AND team_b = 'GHA') OR (team_a = 'GHA' AND team_b = 'CRO'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-27T19:30:00-04:00' WHERE stage = 'group' AND group_name = 'K' AND ((team_a = 'COL' AND team_b = 'POR') OR (team_a = 'POR' AND team_b = 'COL'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-27T19:30:00-04:00' WHERE stage = 'group' AND group_name = 'K' AND ((team_a = 'COD' AND team_b = 'UZB') OR (team_a = 'UZB' AND team_b = 'COD'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-27T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'J' AND ((team_a = 'ALG' AND team_b = 'AUT') OR (team_a = 'AUT' AND team_b = 'ALG'));
UPDATE matches SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3'), match_date = '2026-06-27T22:00:00-04:00' WHERE stage = 'group' AND group_name = 'J' AND ((team_a = 'JOR' AND team_b = 'ARG') OR (team_a = 'ARG' AND team_b = 'JOR'));

-- round_of_32 (16) → Round of 32
WITH ranked AS (
  SELECT id, row_number() OVER (ORDER BY match_date, match_code) AS rn
  FROM matches WHERE stage = 'round_of_32'
), csv(rn, ts) AS (VALUES (1, '2026-06-28T15:00:00-04:00'::timestamptz), (2, '2026-06-29T13:00:00-04:00'::timestamptz), (3, '2026-06-29T16:30:00-04:00'::timestamptz), (4, '2026-06-29T21:00:00-04:00'::timestamptz), (5, '2026-06-30T13:00:00-04:00'::timestamptz), (6, '2026-06-30T17:00:00-04:00'::timestamptz), (7, '2026-06-30T21:00:00-04:00'::timestamptz), (8, '2026-07-01T12:00:00-04:00'::timestamptz), (9, '2026-07-01T16:00:00-04:00'::timestamptz), (10, '2026-07-01T20:00:00-04:00'::timestamptz), (11, '2026-07-02T15:00:00-04:00'::timestamptz), (12, '2026-07-02T19:00:00-04:00'::timestamptz), (13, '2026-07-02T23:00:00-04:00'::timestamptz), (14, '2026-07-03T14:00:00-04:00'::timestamptz), (15, '2026-07-03T18:00:00-04:00'::timestamptz), (16, '2026-07-03T21:30:00-04:00'::timestamptz))
UPDATE matches m SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Round of 32'), match_date = csv.ts
FROM ranked JOIN csv ON csv.rn = ranked.rn WHERE m.id = ranked.id;

-- round_of_16 (8) → Round of 16
WITH ranked AS (
  SELECT id, row_number() OVER (ORDER BY match_date, match_code) AS rn
  FROM matches WHERE stage = 'round_of_16'
), csv(rn, ts) AS (VALUES (1, '2026-07-04T13:00:00-04:00'::timestamptz), (2, '2026-07-04T17:00:00-04:00'::timestamptz), (3, '2026-07-05T16:00:00-04:00'::timestamptz), (4, '2026-07-05T20:00:00-04:00'::timestamptz), (5, '2026-07-06T15:00:00-04:00'::timestamptz), (6, '2026-07-06T20:00:00-04:00'::timestamptz), (7, '2026-07-07T12:00:00-04:00'::timestamptz), (8, '2026-07-07T16:00:00-04:00'::timestamptz))
UPDATE matches m SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Round of 16'), match_date = csv.ts
FROM ranked JOIN csv ON csv.rn = ranked.rn WHERE m.id = ranked.id;

-- quarterfinal (4) → Quarter-finals
WITH ranked AS (
  SELECT id, row_number() OVER (ORDER BY match_date, match_code) AS rn
  FROM matches WHERE stage = 'quarterfinal'
), csv(rn, ts) AS (VALUES (1, '2026-07-09T16:00:00-04:00'::timestamptz), (2, '2026-07-10T15:00:00-04:00'::timestamptz), (3, '2026-07-11T17:00:00-04:00'::timestamptz), (4, '2026-07-11T21:00:00-04:00'::timestamptz))
UPDATE matches m SET matchday_id = (SELECT id FROM matchdays WHERE wc_stage = 'Quarter-finals'), match_date = csv.ts
FROM ranked JOIN csv ON csv.rn = ranked.rn WHERE m.id = ranked.id;

-- semifinal (2) — off-season, matchday_id NULL
WITH ranked AS (
  SELECT id, row_number() OVER (ORDER BY match_date, match_code) AS rn
  FROM matches WHERE stage = 'semifinal'
), csv(rn, ts) AS (VALUES (1, '2026-07-14T15:00:00-04:00'::timestamptz), (2, '2026-07-15T15:00:00-04:00'::timestamptz))
UPDATE matches m SET matchday_id = NULL, match_date = csv.ts
FROM ranked JOIN csv ON csv.rn = ranked.rn WHERE m.id = ranked.id;

-- third_place (1) — off-season, matchday_id NULL
WITH ranked AS (
  SELECT id, row_number() OVER (ORDER BY match_date, match_code) AS rn
  FROM matches WHERE stage = 'third_place'
), csv(rn, ts) AS (VALUES (1, '2026-07-18T17:00:00-04:00'::timestamptz))
UPDATE matches m SET matchday_id = NULL, match_date = csv.ts
FROM ranked JOIN csv ON csv.rn = ranked.rn WHERE m.id = ranked.id;

-- final (1) — off-season, matchday_id NULL
WITH ranked AS (
  SELECT id, row_number() OVER (ORDER BY match_date, match_code) AS rn
  FROM matches WHERE stage = 'final'
), csv(rn, ts) AS (VALUES (1, '2026-07-19T15:00:00-04:00'::timestamptz))
UPDATE matches m SET matchday_id = NULL, match_date = csv.ts
FROM ranked JOIN csv ON csv.rn = ranked.rn WHERE m.id = ranked.id;

COMMIT;
