-- Generated by sync-schedule.mjs --insert-groups=C,D,G,I. Run in the Supabase SQL editor.
-- Inserts missing group-stage matches (idempotent: guarded by NOT EXISTS).
BEGIN;

-- Group C (6 matches)
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'C01', 'BRA', 'MAR', '2026-06-13T18:00:00-04:00'::timestamptz, 'C', 'upcoming', 'MetLife Stadium, East Rutherford', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'C'
    AND ((team_a = 'BRA' AND team_b = 'MAR') OR (team_a = 'MAR' AND team_b = 'BRA'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'C02', 'HAI', 'SCO', '2026-06-13T21:00:00-04:00'::timestamptz, 'C', 'upcoming', 'Gillette Stadium, Foxborough', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'C'
    AND ((team_a = 'HAI' AND team_b = 'SCO') OR (team_a = 'SCO' AND team_b = 'HAI'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'C03', 'SCO', 'MAR', '2026-06-19T18:00:00-04:00'::timestamptz, 'C', 'upcoming', 'Gillette Stadium, Foxborough', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'C'
    AND ((team_a = 'SCO' AND team_b = 'MAR') OR (team_a = 'MAR' AND team_b = 'SCO'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'C04', 'BRA', 'HAI', '2026-06-19T20:30:00-04:00'::timestamptz, 'C', 'upcoming', 'Lincoln Financial Field, Philadelphia', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'C'
    AND ((team_a = 'BRA' AND team_b = 'HAI') OR (team_a = 'HAI' AND team_b = 'BRA'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'C05', 'SCO', 'BRA', '2026-06-24T18:00:00-04:00'::timestamptz, 'C', 'upcoming', 'Hard Rock Stadium, Miami Gardens', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'C'
    AND ((team_a = 'SCO' AND team_b = 'BRA') OR (team_a = 'BRA' AND team_b = 'SCO'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'C06', 'MAR', 'HAI', '2026-06-24T18:00:00-04:00'::timestamptz, 'C', 'upcoming', 'Mercedes-Benz Stadium, Atlanta', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'C'
    AND ((team_a = 'MAR' AND team_b = 'HAI') OR (team_a = 'HAI' AND team_b = 'MAR'))
);

-- Group D (6 matches)
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'D01', 'USA', 'PAR', '2026-06-12T21:00:00-04:00'::timestamptz, 'D', 'upcoming', 'SoFi Stadium, Inglewood', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'D'
    AND ((team_a = 'USA' AND team_b = 'PAR') OR (team_a = 'PAR' AND team_b = 'USA'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'D02', 'AUS', 'TUR', '2026-06-14T00:00:00-04:00'::timestamptz, 'D', 'upcoming', 'BC Place, Vancouver', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'D'
    AND ((team_a = 'AUS' AND team_b = 'TUR') OR (team_a = 'TUR' AND team_b = 'AUS'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'D03', 'USA', 'AUS', '2026-06-19T15:00:00-04:00'::timestamptz, 'D', 'upcoming', 'Lumen Field, Seattle', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'D'
    AND ((team_a = 'USA' AND team_b = 'AUS') OR (team_a = 'AUS' AND team_b = 'USA'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'D04', 'TUR', 'PAR', '2026-06-19T23:00:00-04:00'::timestamptz, 'D', 'upcoming', 'Levi''s Stadium, Santa Clara', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'D'
    AND ((team_a = 'TUR' AND team_b = 'PAR') OR (team_a = 'PAR' AND team_b = 'TUR'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'D05', 'TUR', 'USA', '2026-06-25T22:00:00-04:00'::timestamptz, 'D', 'upcoming', 'SoFi Stadium, Inglewood', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'D'
    AND ((team_a = 'TUR' AND team_b = 'USA') OR (team_a = 'USA' AND team_b = 'TUR'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'D06', 'PAR', 'AUS', '2026-06-25T22:00:00-04:00'::timestamptz, 'D', 'upcoming', 'Levi''s Stadium, Santa Clara', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'D'
    AND ((team_a = 'PAR' AND team_b = 'AUS') OR (team_a = 'AUS' AND team_b = 'PAR'))
);

-- Group G (6 matches)
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'G01', 'BEL', 'EGY', '2026-06-15T15:00:00-04:00'::timestamptz, 'G', 'upcoming', 'Lumen Field, Seattle', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'G'
    AND ((team_a = 'BEL' AND team_b = 'EGY') OR (team_a = 'EGY' AND team_b = 'BEL'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'G02', 'IRN', 'NZL', '2026-06-15T21:00:00-04:00'::timestamptz, 'G', 'upcoming', 'SoFi Stadium, Inglewood', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'G'
    AND ((team_a = 'IRN' AND team_b = 'NZL') OR (team_a = 'NZL' AND team_b = 'IRN'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'G03', 'BEL', 'IRN', '2026-06-21T15:00:00-04:00'::timestamptz, 'G', 'upcoming', 'SoFi Stadium, Inglewood', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'G'
    AND ((team_a = 'BEL' AND team_b = 'IRN') OR (team_a = 'IRN' AND team_b = 'BEL'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'G04', 'NZL', 'EGY', '2026-06-21T21:00:00-04:00'::timestamptz, 'G', 'upcoming', 'BC Place, Vancouver', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'G'
    AND ((team_a = 'NZL' AND team_b = 'EGY') OR (team_a = 'EGY' AND team_b = 'NZL'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'G05', 'EGY', 'IRN', '2026-06-26T23:00:00-04:00'::timestamptz, 'G', 'upcoming', 'Lumen Field, Seattle', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'G'
    AND ((team_a = 'EGY' AND team_b = 'IRN') OR (team_a = 'IRN' AND team_b = 'EGY'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'G06', 'NZL', 'BEL', '2026-06-26T23:00:00-04:00'::timestamptz, 'G', 'upcoming', 'BC Place, Vancouver', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'G'
    AND ((team_a = 'NZL' AND team_b = 'BEL') OR (team_a = 'BEL' AND team_b = 'NZL'))
);

-- Group I (6 matches)
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'I01', 'FRA', 'SEN', '2026-06-16T15:00:00-04:00'::timestamptz, 'I', 'upcoming', 'MetLife Stadium, East Rutherford', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'I'
    AND ((team_a = 'FRA' AND team_b = 'SEN') OR (team_a = 'SEN' AND team_b = 'FRA'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'I02', 'IRQ', 'NOR', '2026-06-16T18:00:00-04:00'::timestamptz, 'I', 'upcoming', 'Gillette Stadium, Foxborough', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD1')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'I'
    AND ((team_a = 'IRQ' AND team_b = 'NOR') OR (team_a = 'NOR' AND team_b = 'IRQ'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'I03', 'FRA', 'IRQ', '2026-06-22T17:00:00-04:00'::timestamptz, 'I', 'upcoming', 'Lincoln Financial Field, Philadelphia', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'I'
    AND ((team_a = 'FRA' AND team_b = 'IRQ') OR (team_a = 'IRQ' AND team_b = 'FRA'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'I04', 'NOR', 'SEN', '2026-06-22T20:00:00-04:00'::timestamptz, 'I', 'upcoming', 'MetLife Stadium, East Rutherford', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD2')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'I'
    AND ((team_a = 'NOR' AND team_b = 'SEN') OR (team_a = 'SEN' AND team_b = 'NOR'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'I05', 'NOR', 'FRA', '2026-06-26T15:00:00-04:00'::timestamptz, 'I', 'upcoming', 'Gillette Stadium, Foxborough', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'I'
    AND ((team_a = 'NOR' AND team_b = 'FRA') OR (team_a = 'FRA' AND team_b = 'NOR'))
);
INSERT INTO matches (match_code, team_a, team_b, match_date, group_name, status, stadium, stage, matchday_id)
SELECT 'I06', 'SEN', 'IRQ', '2026-06-26T15:00:00-04:00'::timestamptz, 'I', 'upcoming', 'BMO Field, Toronto', 'group',
       (SELECT id FROM matchdays WHERE wc_stage = 'Group Stage MD3')
WHERE NOT EXISTS (
  SELECT 1 FROM matches WHERE stage = 'group' AND group_name = 'I'
    AND ((team_a = 'SEN' AND team_b = 'IRQ') OR (team_a = 'IRQ' AND team_b = 'SEN'))
);

COMMIT;
